### ISSUE TITLE
error: no matching function for call to 'min(uint32_t&, int&)

### ISSUE THREAD

**Issue by hipotenusa** [jrodrigoc/ESP32-LEDC#1]
Hi jrodrigo,

Working with Arduino IDE v1.8,12 (linux mint) in method analogWrite just replacing **min** by **_min** fixes the compiling error.

Thanks for your library!
